### ISSUE TITLE
Add Research Usage

### ISSUE THREAD

**Issue by kkrick-sdsu** [SDSU-Research-CI/SDSU-Research-CI.github.io#40]

**Comment by kkrick-sdsu** [comment]
Reach out to Atsushi Nara, Tingting Tang and Uduak George for short summary and title of research projects using the research cluster.

**Comment by joaquin-mendoza8** [comment]
Reach out to researchers? Who from SDSU-RCI-JH access is actively doing research?

**Comment by joaquin-mendoza8** [comment]
Will update on a rolling basis if Nara or George respond with a research description.
